Repository AWS-Cloud-School-6/AIWA-MCP-Backend-AwsService, pull requests merged in 2024-10, with the labels that each got.

#9 3 feat aws sdk load
  .gitignore
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/workspace.xml
  build.gradle
  build/resources/main/application.properties
  build/resources/main/static/index.html
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceFetcher.class.uniqueId1
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/AwsResourceController.java
  src/main/java/AIWA/McpBackend/AwsResourceFetcher.java
  src/main/java/AIWA/McpBackend/Ec2InstanceDTO.java
  src/main/java/AIWA/McpBackend/McpBackendApplication.java
  src/main/java/AIWA/McpBackend/SecurityGroupDTO.java
  src/main/java/AIWA/McpBackend/SubnetDTO.java
  src/main/java/AIWA/McpBackend/VpcDTO.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
Labels: enhancement

#11 #10 Refac: 디렉토리 재구조화
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .idea/compiler.xml
  .idea/gradle.xml
  src/main/java/AIWA/McpBackend/entity/member/Member.java
  src/main/java/AIWA/McpBackend/provider/MemberController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/AwsResourceFetcher.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/ec2/Ec2InstanceDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/securitygroup/SecurityGroupDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/subnet/SubnetDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/vpc/VpcDTO.java
  src/main/java/AIWA/McpBackend/repository/member/MemberRepository.java
  src/main/java/AIWA/McpBackend/service/member/MemberService.java
Labels: bug

#18 #17 Refactor: Member DTO 및 리소스 Tag값 추가
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  .idea/libraries/Gradle__javax_activation_javax_activation_api_1_2_0.xml
  .idea/libraries/Gradle__javax_xml_bind_jaxb_api_2_3_1.xml
  .idea/modules/AIWA.McpBackend.main.iml
  .idea/modules/McpBackend.iml
  .idea/modules/McpBackend.test.iml
  build.gradle
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceFetcher.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/Ec2InstanceDTO.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/MemberController.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/MemberService.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/S3Service.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityGroupDTO.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/SubnetDTO.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/VpcDTO.class.uniqueId2
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/entity/member/Member.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/awsResource/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/member/MemberController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/ec2/Ec2InstanceDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/memberCredential/MemberCredentialDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/securitygroup/SecurityGroupDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/subnet/SubnetDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/vpc/VpcDTO.java
  src/main/java/AIWA/McpBackend/service/awsResource/AwsResourceService.java
  src/main/resources/application.properties
Labels: enhancement

#19 16 feat vpc create
  .DS_Store
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .idea/libraries/Gradle__com_hierynomus_asn_one_0_6_0.xml
  .idea/libraries/Gradle__com_hierynomus_sshj_0_34_0.xml
  .idea/libraries/Gradle__com_jcraft_jsch_0_1_55.xml
  .idea/libraries/Gradle__com_jcraft_jzlib_1_1_3.xml
  .idea/libraries/Gradle__javax_activation_javax_activation_api_1_2_0.xml
  .idea/libraries/Gradle__javax_xml_bind_jaxb_api_2_3_1.xml
  .idea/libraries/Gradle__net_i2p_crypto_eddsa_0_3_0.xml
  .idea/libraries/Gradle__org_bouncycastle_bcpkix_jdk15on_1_70.xml
  .idea/libraries/Gradle__org_bouncycastle_bcprov_jdk15on_1_70.xml
  .idea/libraries/Gradle__org_bouncycastle_bcutil_jdk15on_1_70.xml
  .idea/libraries/Gradle__org_slf4j_slf4j_api_2_0_16.xml
  .idea/modules/AIWA.McpBackend.iml
  .idea/modules/AIWA.McpBackend.main.iml
  .idea/modules/AIWA.McpBackend.test.iml
  .idea/modules/McpBackend.test.iml
  build.gradle
  build/tmp/compileJava/compileTransaction/stash-dir/TerraformService.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/VpcController.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/VpcService.class.uniqueId1
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/vpc/VpcController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/ec2/Ec2RequestDto.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/vpc/VpcRequestDto.java
  src/main/java/AIWA/McpBackend/service/ec2/Ec2Service.java
  src/main/java/AIWA/McpBackend/service/s3/S3Service.java
  src/main/java/AIWA/McpBackend/service/terraform/TerraformService.java
  src/main/java/AIWA/McpBackend/service/vpc/VpcService.java
Labels: enhancement

#23 22 feat internetgatewayig generation deletion
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/internetgateway/InternetGatewayController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/member/MemberController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/internetgateway/InternetGatewayRequestDto.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/membercredential/MemberCredentialDTO.java
  src/main/java/AIWA/McpBackend/service/internetgateway/InternetGatewayService.java
Labels: enhancement

#25 24 feat route tabele nat gateway generation deletion
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/natgateway/NatGatewayController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/routetable/RouteTableController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/securitygroup/SecurityGroupController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/natgateway/NatGatewayRequestDto.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/routetable/RouteTableRequestDto.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/securitygroup/SecurityGroupRequestDto.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/securitygroup/SecurityGroupRuleDto.java
  src/main/java/AIWA/McpBackend/service/natgateway/NatGatewayService.java
  src/main/java/AIWA/McpBackend/service/routetable/RouteTableService.java
  src/main/java/AIWA/McpBackend/service/securitygroup/SecurityGroupService.java
Labels: enhancement

#27 26 feat ec2 generation deletion
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/ec2/Ec2Controller.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/ec2/Ec2RequestDto.java
  src/main/java/AIWA/McpBackend/service/ec2/Ec2Service.java
Labels: enhancement

#29 28 feat cloudwatch monitoring
  src/main/java/AIWA/McpBackend/config/aws/s3/S3Config.java
  src/main/java/AIWA/McpBackend/provider/aws/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/cloudwatch/CloudWatchController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/ec2/Ec2Controller.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/internetgateway/InternetGatewayController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/natgateway/NatGatewayController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/routetable/RouteTableController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/securitygroup/SecurityGroupController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/subnet/SubnetController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/vpc/VpcController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/cloudwatch/CloudWatchAlarmRequestDto.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
  src/main/java/AIWA/McpBackend/service/aws/cloudwatch/CloudWatchService.java
  src/main/java/AIWA/McpBackend/service/aws/ec2/Ec2Service.java
  src/main/java/AIWA/McpBackend/service/aws/internetgateway/InternetGatewayService.java
  src/main/java/AIWA/McpBackend/service/aws/natgateway/NatGatewayService.java
  src/main/java/AIWA/McpBackend/service/aws/routetable/RouteTableService.java
  src/main/java/AIWA/McpBackend/service/aws/s3/S3Service.java
  src/main/java/AIWA/McpBackend/service/aws/securitygroup/SecurityGroupService.java
  src/main/java/AIWA/McpBackend/service/aws/subnet/SubnetService.java
  src/main/java/AIWA/McpBackend/service/aws/vpc/VpcService.java
  src/main/java/AIWA/McpBackend/service/member/MemberService.java
  src/main/java/AIWA/McpBackend/service/terraform/TerraformService.java
Labels: enhancement

#35 #33 Feat: vpc+subnet set 생성 및 삭제 기능 개발
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/AwsInfraController.class.uniqueId0
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/infra/AwsInfraController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/infra/InfraDeleteRequestDto.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/infra/InfraRequestDto.java
Labels: enhancement

#40 39 test template reco
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  build/reports/tests/test/classes/AIWA.McpBackend.McpBackendApplicationTests.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/AIWA.McpBackend.html
  build/resources/main/application.properties
  build/test-results/test/TEST-AIWA.McpBackend.McpBackendApplicationTests.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/compileTransaction/stash-dir/KmsService.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  build/tmp/jar/MANIFEST.MF
  src/main/java/AIWA/McpBackend/config/AppConfig.java
  src/main/java/AIWA/McpBackend/provider/aws/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/member/MemberController.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
  src/main/java/AIWA/McpBackend/service/kms/KmsService.java
  src/main/java/AIWA/McpBackend/service/member/MemberService.java
  src/main/resources/application.properties
Labels: bug

#44 43 fix cors prob
  src/main/java/AIWA/McpBackend/config/WebConfig.java
  src/main/java/AIWA/McpBackend/service/terraform/TerraformService.java
Labels: bug

#46 #45 create vpc get mapping
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/provider/aws/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/vpc/VpcController.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
Labels: enhancement

#48 #47 Feat: Add get RouteTable
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/AwsInfraController.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/CloudWatchController.class.uniqueId18
  build/tmp/compileJava/compileTransaction/stash-dir/CloudWatchService.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/Ec2Controller.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/Ec2Service.class.uniqueId16
  build/tmp/compileJava/compileTransaction/stash-dir/EipController.class.uniqueId14
  build/tmp/compileJava/compileTransaction/stash-dir/EipService.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/InternetGatewayController.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/InternetGatewayService.class.uniqueId13
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayController.class.uniqueId17
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayService.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/RouteTableController.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/RouteTableDTO.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/RouteTableService.class.uniqueId15
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityGroupController.class.uniqueId11
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityGroupService.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/SubnetController.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/SubnetService.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/TerraformService.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/VpcController.class.uniqueId19
  build/tmp/compileJava/compileTransaction/stash-dir/VpcService.class.uniqueId12
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/provider/aws/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/routetable/RouteTableDTO.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
Labels: enhancement

#50 #49 Feat: Subnet in VPC
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/RouteTableDTO.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/TerraformService.class.uniqueId2
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/provider/aws/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/vpc/VpcController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/routetable/RouteDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/routetable/RouteTableDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/subnet/SubnetDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/vpc/VpcDTO.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
Labels: enhancement

#52 #51 Refac: Member 조회 변수 email로 변경 및 subnet GET api 생성
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .idea/aws.xml
  build/reports/tests/test/classes/AIWA.McpBackend.McpBackendApplicationTests.html
  build/reports/tests/test/index.html
  build/reports/tests/test/packages/AIWA.McpBackend.html
  build/test-results/test/TEST-AIWA.McpBackend.McpBackendApplicationTests.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/bootJar/MANIFEST.MF
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/MemberController.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/jar/MANIFEST.MF
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/member/MemberController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/subnet/SubnetController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/vpc/VpcController.java
Labels: enhancement

#54 #53 Refac: describe-subnet 에 az 추가
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceController.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceService.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/MemberController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/SubnetController.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/SubnetDTO.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/VpcController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/VpcDTO.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/subnet/SubnetDTO.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
Labels: enhancement

#58 57 feat resource sdk describe
  src/main/java/AIWA/McpBackend/provider/aws/AwsResourceController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/ec2/Ec2Controller.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/eip/EipController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/internetgateway/InternetGatewayController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/natgateway/NatGatewayController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/routetable/RouteTableController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/securitygroup/SecurityGroupController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/subnet/SubnetController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/vpc/VpcController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/eip/EipDto.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/natgateway/NatGatewayDto.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
Labels: bug, enhancement

#64 #63 Feat: natgateway에 eni public ip 추가
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceController.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceService.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceService.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/Ec2Controller.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayController.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayDto.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/NetworkInterfaceController.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/RouteTableController.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityGroupController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/SubnetController.class.uniqueId4
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/eni/NetworkInterfaceDto.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
Labels: enhancement

#67 66 feat cloud sql
  .github/workflows/main.yml
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  .idea/dataSources.xml
  .idea/libraries/Gradle__com_amazonaws_aws_java_sdk_kms_1_12_574.xml
  .idea/libraries/Gradle__com_h2database_h2_2_2_224.xml
  .idea/libraries/Gradle__software_amazon_awssdk_annotations_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_apache_client_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_auth_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_aws_core_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_aws_json_protocol_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_endpoints_spi_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_http_client_spi_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_json_utils_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_kms_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_metrics_spi_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_netty_nio_client_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_profiles_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_protocol_core_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_regions_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_sdk_core_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_third_party_jackson_core_2_20_100.xml
  .idea/libraries/Gradle__software_amazon_awssdk_utils_2_20_100.xml
  .idea/modules/AIWA.McpBackend.main.iml
  .idea/modules/McpBackend.iml
  .idea/modules/McpBackend.test.iml
  build.gradle
  build/tmp/compileJava/previous-compilation-data.bin
  dockerfile
  src/main/resources/application.properties
Labels: enhancement

#68 #65 Member 삭제 추가
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/modules/AIWA.McpBackend.main.iml
  .idea/modules/McpBackend.test.iml
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/member/MemberController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/membercredential/MemberDeleteRequestDto.java
  src/main/java/AIWA/McpBackend/service/aws/s3/S3Service.java
  src/main/java/AIWA/McpBackend/service/member/MemberService.java
Labels: enhancement

#70 #69 Docs: main.yaml CI 통합, CD 전체 삭제
  .github/workflows/main.yml
Labels: documentation

#72 71 fix mainyaml image build error 수정
  .github/workflows/main.yml
Labels: documentation

#74 #73 Docs: main.yaml helm 코드 수정
  .github/workflows/main.yml
Labels: documentation

#76 #75 Fix: eip 생성, 삭제 (connect, disconnect 개발중)
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/reports/tests/test/classes/AIWA.McpBackend.McpBackendApplicationTests.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/AIWA.McpBackend.html
  build/resolvedMainClassName
  build/test-results/test/TEST-AIWA.McpBackend.McpBackendApplicationTests.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/bootJar/MANIFEST.MF
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceController.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/AwsResourceService.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/Ec2Controller.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/EipController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/InternetGatewayController.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayController.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/NetworkInterfaceController.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/RouteTableController.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityGroupController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/SubnetController.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/VpcController.class.uniqueId2
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  build/tmp/jar/MANIFEST.MF
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/eip/EipController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/eip/EipRequestDto.java
  src/main/java/AIWA/McpBackend/service/aws/eip/EipService.java
Labels: bug, fix

#79 #77 Feat: natgateway에 allocateId 추가
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayController.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayService.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/natgateway/NatGatewayRequestDto.java
  src/main/java/AIWA/McpBackend/service/aws/natgateway/NatGatewayService.java
Labels: enhancement

#81 #80 Fix: MSA 구조 변경 후 TerraformPod 으로 명령어 전달하는 방식으로 수정
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  .idea/modules/AIWA.McpBackend.main.iml
  .idea/modules/McpBackend.test.iml
  build.gradle
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayController.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/NatGatewayService.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/service/terraform/TerraformService.java
Labels: fix

#83 #82 Feat: api 경로 수정
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  src/main/java/AIWA/McpBackend/service/terraform/TerraformService.java
Labels: enhancement

#85 #84 Fix: api route update
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/member/MemberController.java
  src/main/java/AIWA/McpBackend/provider/aws/api/controller/vpc/VpcController.java
Labels: fix

#91 #86 Member Service seperate and connect
  build.gradle
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/member/MemberCredentialDTO.java
  src/main/java/AIWA/McpBackend/provider/aws/api/dto/member/MemberDTO.java
  src/main/java/AIWA/McpBackend/service/aws/AwsResourceService.java
  src/main/java/AIWA/McpBackend/service/aws/s3/S3Service.java
  src/main/resources/application.properties
Labels: enhancement, fix
